# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates Pyre with GitHub's
# Code Scanning feature.
#
# Pyre is a performant type checker for Python compliant with
# PEP 484. Pyre can analyze codebases with millions of lines
# of code incrementally – providing instantaneous feedback
# to developers as they write code.
#
# See https://pyre-check.org

name: Pyre

on:
  workflow_dispatch:
  push:
    branches: [ "main", "aNerdFromDuval-dev" ]
  pull_request:
    branches: [ "main" ]

permissions:
    contents: read

jobs:
  pyre:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install cython flask flask_cors graphql-core typing_inspect
        VERSION=$(grep "version" .pyre_configuration | sed -n -e 's/.*\(0\.0\.[0-9]*\).*/\1/p')
        pip install pyre-check-nightly==$VERSION

    - name: Run Pyre
      continue-on-error: true
      run: |
        pyre --output=sarif check > sarif.json

    - name: Expose SARIF Results
      uses: actions/upload-artifact@v2
      with:
        name: SARIF Results
        path: sarif.json

    - name: Upload SARIF Results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: sarif.json

    - name: Fail Command On Errors
      run: |
        if [ "$(cat sarif.json | grep 'PYRE-ERROR')" != "" ]; then cat sarif.json && exit 1; fi
